[project]
name = "conversor-medidas"
version = "0.1.0"
dependencies = ["typer==0.12.5","rich==13.7.1"]
[project.optional-dependencies]
dev = ["pytest==8.3.2"]

[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"