# .github/workflows/auto-run.yml
name: Workflow Automático

on:
  schedule:
    - cron: "0 0 * * *"   # todo dia à meia-noite (UTC)
  workflow_dispatch:       # também permite rodar manualmente, se quiser

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar mensagem
        run: echo "Este workflow iniciou sozinho 🎉"
