name: Hello World Workflow

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Hello World
        uses: ./.github/actions/hello

      - name: Mostrar saída
        run: | 
          echo "Mensagem recebida: ${{ steps.hello.outputs.msg }}"